# PyTorch - Tensors

In [1]:
import torch 
import torchvision

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## tensor init

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
data

[[1, 2], [3, 4]]

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [18]:
np_array = np.arange(128)
np_array = np_array.reshape((4, 4, 8))
np_array

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31]],

       [[ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]]])

In [19]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31]],

        [[ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]],

        [[ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87],
         [ 88,  89,  90,  91,  92,  93,  94,  95]],

        [[ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127]]])

In [20]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]]])

In [23]:
x_rand = torch.rand_like(x_ones, dtype=torch.float) # overrides the datatype of x_data
x_rand

tensor([[[0.4760, 0.1663, 0.4084, 0.5064, 0.9158, 0.8652, 0.9199, 0.7916],
         [0.3047, 0.3542, 0.6401, 0.9714, 0.8601, 0.2772, 0.7217, 0.8921],
         [0.6422, 0.3755, 0.1743, 0.2959, 0.8030, 0.4400, 0.8561, 0.2267],
         [0.9233, 0.0238, 0.7237, 0.4783, 0.6117, 0.4202, 0.7439, 0.3052]],

        [[0.9394, 0.7837, 0.9180, 0.4957, 0.2925, 0.8229, 0.9913, 0.3103],
         [0.9355, 0.8551, 0.1137, 0.1200, 0.8066, 0.7790, 0.8421, 0.2506],
         [0.3491, 0.9713, 0.5080, 0.5263, 0.8180, 0.3900, 0.7802, 0.0925],
         [0.4487, 0.8491, 0.1479, 0.3451, 0.3105, 0.1481, 0.8415, 0.0953]],

        [[0.1107, 0.2632, 0.1154, 0.1395, 0.8261, 0.7461, 0.2947, 0.5907],
         [0.6090, 0.6063, 0.0619, 0.8951, 0.9164, 0.8504, 0.8832, 0.4710],
         [0.7635, 0.2490, 0.7474, 0.9647, 0.0849, 0.7642, 0.8319, 0.8889],
         [0.9565, 0.6617, 0.9228, 0.1925, 0.3112, 0.6913, 0.4395, 0.5653]],

        [[0.9574, 0.7077, 0.8645, 0.4048, 0.1549, 0.7943, 0.9601, 0.9007],
         [0.0448, 0

In [28]:
shape = (2, 3, )

rand_tensor = torch.rand(shape)
print("rand_tensor", rand_tensor)
ones_tensor = torch.ones(shape)
print("\nones_tensor", ones_tensor)
zeros_tensor = torch.zeros(shape)
print("\nzeros_tensor", zeros_tensor)

rand_tensor tensor([[0.1251, 0.0958, 0.4570],
        [0.1323, 0.6755, 0.8321]])

ones_tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
rand_tensor.shape

torch.Size([2, 3])

In [30]:
rand_tensor.dtype

torch.float32

In [32]:
rand_tensor.device

device(type='cpu')