# PyTorch - Tensors

In [25]:
import torch 
import torchvision

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## tensor init

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
data

[[1, 2], [3, 4]]

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.arange(128)
np_array = np_array.reshape((4, 4, 8))
np_array

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31]],

       [[ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]]])

In [7]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31]],

        [[ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]],

        [[ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87],
         [ 88,  89,  90,  91,  92,  93,  94,  95]],

        [[ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127]]])

In [8]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]]])

In [9]:
x_rand = torch.rand_like(x_ones, dtype=torch.float) # overrides the datatype of x_data
x_rand

tensor([[[0.3557, 0.1341, 0.2033, 0.7348, 0.8554, 0.8290, 0.0845, 0.3573],
         [0.5866, 0.1522, 0.7962, 0.7270, 0.8095, 0.3678, 0.6846, 0.2545],
         [0.3538, 0.2396, 0.3523, 0.8158, 0.6269, 0.5914, 0.9062, 0.4684],
         [0.7768, 0.0899, 0.7386, 0.2507, 0.3541, 0.1800, 0.9163, 0.8482]],

        [[0.9154, 0.2534, 0.1331, 0.2865, 0.4299, 0.2208, 0.1028, 0.8366],
         [0.5412, 0.4938, 0.7855, 0.0899, 0.1704, 0.9589, 0.2459, 0.9939],
         [0.4077, 0.7253, 0.8149, 0.7357, 0.8692, 0.6532, 0.2709, 0.3904],
         [0.9061, 0.0745, 0.4010, 0.8446, 0.6205, 0.9482, 0.4752, 0.7959]],

        [[0.2039, 0.0815, 0.8293, 0.7921, 0.9690, 0.5543, 0.2195, 0.6032],
         [0.1041, 0.3714, 0.8700, 0.5070, 0.3058, 0.1406, 0.1312, 0.2512],
         [0.5899, 0.0781, 0.5091, 0.4677, 0.7825, 0.3330, 0.5372, 0.5312],
         [0.4430, 0.1320, 0.7899, 0.0563, 0.0106, 0.2092, 0.6134, 0.6724]],

        [[0.1512, 0.7957, 0.3477, 0.2929, 0.4269, 0.2167, 0.7989, 0.5977],
         [0.7807, 0

In [10]:
shape = (2, 3, )

rand_tensor = torch.rand(shape)
print("rand_tensor", rand_tensor)
ones_tensor = torch.ones(shape)
print("\nones_tensor", ones_tensor)
zeros_tensor = torch.zeros(shape)
print("\nzeros_tensor", zeros_tensor)

rand_tensor tensor([[0.5422, 0.5602, 0.3106],
        [0.8988, 0.5179, 0.1956]])

ones_tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
rand_tensor.shape

torch.Size([2, 3])

In [12]:
rand_tensor.dtype

torch.float32

In [13]:
rand_tensor.device

device(type='cpu')

In [17]:
tensor = torch.rand(5, 4)
tensor

tensor([[0.5909, 0.2101, 0.7176, 0.2078],
        [0.0787, 0.7132, 0.7797, 0.7012],
        [0.0812, 0.4989, 0.8068, 0.5502],
        [0.6067, 0.3477, 0.3143, 0.6903],
        [0.2363, 0.1418, 0.0132, 0.3239]])

In [18]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Tensor is on: {tensor.device}")

Tensor is on: cuda:0


In [20]:
tensor[:, 3]

tensor([0.2078, 0.7012, 0.5502, 0.6903, 0.3239], device='cuda:0')

In [31]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor[1, :] = 2
tensor

tensor([[1., 0., 1., 1.],
        [2., 2., 2., 2.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
tensor = torch.cat(tensors=[tensor, tensor, tensor], dim=0)
tensor

tensor([[1., 0., 1., 1.],
        [2., 2., 2., 2.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [2., 2., 2., 2.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [2., 2., 2., 2.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [33]:
tensor = torch.cat(tensors=[tensor, tensor, tensor], dim=1)
tensor

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [34]:
tensor.shape

torch.Size([12, 12])

# element wise multiplication

In [35]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [36]:
tensor * tensor

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

# matrix multiplication

In [37]:
tensor.matmul(tensor.T)

tensor([[ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [18., 48., 18., 18., 18., 48., 18., 18., 18., 48., 18., 18.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [18., 48., 18., 18., 18., 48., 18., 18., 18., 48., 18., 18.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [18., 48., 18., 18., 18., 48., 18., 18., 18., 48., 18., 18.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.],
        [ 9., 18.,  9.,  9.,  9., 18.,  9.,  9.,  9., 18.,  9.,  9.]])

In [39]:
tensor.T @ tensor

tensor([[21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.],
        [21., 12., 21., 21., 21., 12., 21., 21., 21., 12., 21., 21.]])

## in place operations (discouraged due to history loss)

In [ ]:
tensor.add_(1)

tensor([[2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.],
        [2., 1., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2.]])

# bridging over to numpy

In [50]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [51]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [52]:
# note that the two are connected
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [53]:
# goes around as well
n = np.ones(10)
t = torch.from_numpy(n)
n, t

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [54]:
np.add(n, 4, out=n)
t, n

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.], dtype=torch.float64),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))